name: Deploy SAM Lambda

on:
  push:
    branches:
      - master  # Trigger on push to main branch (change if needed)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install AWS SAM CLI
        run: pip install aws-sam-cli

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: SAM Build
        run: sam build

      - name: SAM Package
        run: |
          sam package \
            --output-template-file packaged.yaml \
            --s3-bucket jenkinsdir1

      - name: SAM Deploy
        run: |
          sam deploy \
            --template-file packaged.yaml \
            --stack-name kalyan-lambda-sam-app \
            --capabilities CAPABILITY_IAM CAPABILITY_AUTO_EXPAND \
            --region us-east-1 \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset
