name: Deploy SAM Lambda (Branch-Based Environment)

on:
  workflow_dispatch:
    inputs:
      s3_bucket:
        description: "S3 Bucket for Artifacts"
        required: true
        default: "jenkinsdir1"

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_DEFAULT_REGION: us-east-1
      ENV_NAME: ${{ github.ref_name }}
      APP_NAME: nomo-lambdas-${{ github.ref_name }}
      S3_BUCKET: ${{ github.event.inputs.s3_bucket }}
      S3_BUCKET_PREFIX: nomo-lambdas-${{ github.ref_name }}-artifacts

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install AWS SAM CLI
        run: pip install aws-sam-cli

      - name: Configure AWS Credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::571600831534:role/github-actions-sam-deploy-role
          aws-region: us-east-1

      - name: SAM Build
        run: sam build

      - name: SAM Package
        run: |
          sam package \
            --output-template-file packaged.yaml \
            --s3-bucket ${{ env.S3_BUCKET }} \
            --s3-prefix ${{ env.S3_BUCKET_PREFIX }}

      - name: SAM Deploy
        run: |
          sam deploy \
            --template-file packaged.yaml \
            --stack-name ${{ env.APP_NAME }} \
            --capabilities CAPABILITY_IAM CAPABILITY_AUTO_EXPAND \
            --region ${{ env.AWS_DEFAULT_REGION }} \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset \
            --parameter-overrides \
              Environment=${{ env.ENV_NAME }} \
              S3Bucket=${{ env.S3_BUCKET }} \
              S3Prefix=${{ env.S3_BUCKET_PREFIX }}
